routes/web.php
<?php

use App\Http\Controllers\MovieController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::get('/movie-detail', [MovieController::class, 'detail'])->name('movie.detail');
Route::get('/movie-search', [MovieController::class, 'search'])->name('movie.search');

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;

use App\Traits\CreatedAtTrait;
use App\Traits\UpdatedAtTrait;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;
use Spatie\MediaLibrary\HasMedia;
use Spatie\MediaLibrary\InteractsWithMedia;
use Spatie\MediaLibrary\MediaCollections\Models\Media;

class User extends Authenticatable implements HasMedia
{
    use HasApiTokens, HasFactory, Notifiable, CreatedAtTrait, UpdatedAtTrait, InteractsWithMedia, SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'phone',
        'password',
        'birthday',
        'gender',
        'email_verified_at'
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'password' => 'hashed',
    ];

    public function registerMediaConversions(Media $media = null): void
    {
        $this->addMediaConversion('table')
            ->width(368)
            ->height(232)
            ->sharpen(10);
    }

    public function getImageAttribute()
    {
        if ($this->getFirstMediaUrl('User')) {
            return $this->getFirstMediaUrl('User');
        } else {
            return url('images/logo.jpg');
        }
    }

    public function setPasswordAttribute($value)
    {
        $this->attributes['password'] = bcrypt($value);
    }
}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <input type="search" id="searchMovie" class="form-control" placeholder="Find Movie here" name="search">
                <br>
                <div class="card">
                    <div class="card-header">
                        <label>Movies</label>
                    </div>
                    <div class="card-body">
                        <select class="form-control" id="categories">
                            <option value="">Choose Category</option>
                            @foreach ($categories as $category)
                                <option value="{{ $category->id }}">{{ $category->name }}</option>
                            @endforeach
                        </select>
                        <div class="row" id="movies">
                            @foreach ($movies as $movie)
                                <div class="col-md-4">
                                    <div class="card m-2">
                                        <div class="card-header">
                                            <label>{{ $movie->name }}</label>
                                        </div>
                                        <div class="card-body">
                                            <a href="{{ route('movie.detail', ['id' => $movie->id]) }}">
                                                <img src="{{ $movie->image }}" alt="movie image"
                                                    style="width:170px;height:150px;">
                                            </a>
                                        </div>
                                        <div class="card-footer">
                                            <p>{{ Str::limit($movie->description, 20) }}</p>
                                        </div>
                                        @foreach ($movie->categories as $category)
                                            <span class="badge rounded-pill badge-light-info"
                                                style="font-size: 14px;color: darkgoldenrod;">{{ $category->name }}</span>
                                        @endforeach
                                    </div>
                                </div>
                            @endforeach
                        </div>

                        {{ $movies->links() }}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('scripts')
    <script>
        $('#categories').on('change', function(e) {
            e.preventDefault();

            $.ajax({
                url: "{{ route('movie.search') }}",
                type: "GET",
                data: {
                    _token: '{{ csrf_token() }}',
                    category_id: $(this).find(":selected").val(),
                    search: $('searchMovie').value,
                },
                success: function(response, textStatus, xhr) {
                    $('#movies').empty();
                    console.log(response.movies.data);
                    response.movies.data.forEach(movie => {
                        let movieDetailRoute = route('movie.detail', {
                            id: movie.id
                        });
                        var movieEle =
                            `<div class="col-md-4">
                                <div class="card m-2">
                                    <div class="card-header">
                                        <label>${movie.name}</label>
                                    </div>
                                    <div class="card-body">
                                        <a href="${movieDetailRoute}">
                                            <img src="${movie.image}" alt="movie image"
                                                style="width:170px;height:150px;">
                                        </a>
                                    </div>
                                    <div class="card-footer">
                                        <p>${movie.description.substring(0,20)}</p>
                                    </div>`;

                        movie.categories.forEach(category => {
                            movieEle += `<span class="badge rounded-pill badge-light-info" 
                                                style="font-size: 14px;color: darkgoldenrod;">${category.name}</span>`;
                        });

                        movieEle += '</div></div>';

                        $('#movies').append(movieEle);
                    });
                },
                error: function(response) {
                    alert(response);
                }
            });
        });

        $('#searchMovie').keyup(function(e) {
            e.preventDefault();

            $.ajax({
                url: "{{ route('movie.search') }}",
                type: "GET",
                data: {
                    _token: '{{ csrf_token() }}',
                    search: this.value,
                    category_id: $('#categories').find(":selected").val()
                },
                success: function(response, textStatus, xhr) {
                    $('#movies').empty();
                    console.log(response.movies.data);
                    response.movies.data.forEach(movie => {
                        let movieDetailRoute = route('movie.detail', {
                            id: movie.id
                        });
                        var movieEle =
                            `<div class="col-md-4">
                                <div class="card m-2">
                                    <div class="card-header">
                                        <label>${movie.name}</label>
                                    </div>
                                    <div class="card-body">
                                        <a href="${movieDetailRoute}">
                                            <img src="${movie.image}" alt="movie image"
                                                style="width:170px;height:150px;">
                                        </a>
                                    </div>
                                    <div class="card-footer">
                                        <p>${movie.description.substring(0,20)}</p>
                                    </div>`;

                        movie.categories.forEach(category => {
                            movieEle += `<span class="badge rounded-pill badge-light-info" 
                                    style="font-size: 14px;color: darkgoldenrod;">${category.name}</span>`;
                        });

                        movieEle += '</div></div>';

                        $('#movies').append(movieEle);
                    });
                },
                error: function(response) {
                    alert(response);
                }
            });
        });
    </script>
@endsection

resources/views/movie-detail.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">
                        <div class="row">
                            <div class="col-md-6">
                                <label>Movies Detail</label>
                            </div>
                            <div class="col-md-6">
                                <a href="{{ route('home') }}"
                                    style="display: flex;justify-content: flex-end;text-decoration: none;">Back</a>
                            </div>
                        </div>
                    </div>
                    <div class="card-body">
                        <p>Name: {{ $movie->name }}</p>
                        <img src="{{ $movie->image }}" alt="movie image"
                            style="width:300px;height:300px;">
                        <p>Description: {{ $movie->description }}</p>
                        @if($movie->categories->count() > 0)
                            <h3>Categories List</h3>
                        @endif
                        @foreach ($movie->categories as $category)
                            <span class="badge rounded-pill badge-light-info" 
                                style="font-size: 14px;color: darkgoldenrod;">{{ $category->name }}</span>
                        @endforeach
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection